### ISSUE TITLE
pagerduty_key and pagerduty.key required on node when using nagios_pagerduty data bag

### ISSUE THREAD

**Issue by cleveranecdote** [tas50/nagios#252] opened 2014-03-06 18:00 UTC
Chef run fails on nagios node puts pagerduty.key = null in the node.
Tried making it a number or string, as well as deleting it entirely and it would always come back as null.

Workaround is to have a fake value for both pagerduty.key and pagerduty_key:

"nagios": {
     "pagerduty_key": "999",
     "pagerduty": {
       "key": "888"
     },

After chef run completed successfully the node shows
"nagios": {
     "pagerduty_key": "888",
     "pagerduty": {
       "key": "888"
     },

/etc/nagios3/conf/pagerduty.cfg has a contact of 888 as well as my data bag one.

Please make that section in the node not required if using a data bag.

**Comment by sbotman** [comment] 2015-05-19 08:02
The pagerduty information is moved into LWRP logic. Closing this ticket because think the issue is solved. Please feel free to reopen if needed.

**Closed by sbotman** 2015-05-19 08:02 UTC
