### ISSUE TITLE
Add environment list support

### ISSUE THREAD

**Issue by kozdincer** [tas50/nagios#238] opened 2014-01-30 13:16 UTC
When we use to multi_environment feauture, we can use environment_list for just what we want to see on nagios. Or environment_exception_list for what we dont want to.

**Comment by sbotman** [comment] 2015-05-19 08:00
@kozdincer Think that this ticket is not really an issue anymore. With the new setup you can filter and include any configuration that you like. I'm closing this but feel free to reopen or open another ticket if the issue is still relevant.

**Closed by sbotman** 2015-05-19 08:00 UTC
