### ISSUE TITLE
Duplicate commands check-host-alive, check_nrpe

### ISSUE THREAD

**Issue by wayne530** [tas50/nagios#286] opened 2014-06-28 20:45 UTC
On Ubuntu 12.04, the nagios-plugins* packages already include checks with these names:

 % grep check-host-alive *
ping.cfg:# 'check-host-alive' command definition
ping.cfg:	command_name	check-host-alive
ping.cfg:# 'check-host-alive_4' command definition
ping.cfg:	command_name	check-host-alive_4
 % grep check_nrpe *
check_nrpe.cfg:	command_name	check_nrpe
check_nrpe.cfg:	command_line	/usr/lib/nagios/plugins/check_nrpe -H $HOSTADDRESS$ -c $ARG1$ -a $ARG2$
check_nrpe.cfg:	command_name	check_nrpe_1arg
check_nrpe.cfg:	command_line	/usr/lib/nagios/plugins/check_nrpe -H $HOSTADDRESS$ -c $ARG1$

This causes Nagios not to startup due to duplicate command definitions.

**Comment by sbotman** [comment] 2015-03-02 14:48
from version 7 you should be able to configure any type of configuration option. So this should be solved by now. On the other hand, if other packages drop configuration files into the nagios/conf.d directory that have other names than the current templates, then these are not cleared and could still collide with configuration settings.

**Comment by sbotman** [comment] 2015-05-18 23:43
The addition of the zap cookbook and cleaning out the conf dir should solve this problem I state here above. 

I'm closing this because I think the problem is solved within the latest version. But please feel free to reopen or create a new ticket if needed.

Greetings Sander

**Closed by sbotman** 2015-05-18 23:43 UTC
